name: CI

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/*"
  workflow_dispatch:

jobs:
  ci-master:
    if: github.ref == 'refs/heads/master'
    uses: org/reusable-workflows/.github/workflows/reusable-ci.yml@main
    with:
      branch: "master"

  ci-develop:
    if: github.ref == 'refs/heads/develop'
    uses: org/reusable-workflows/.github/workflows/reusable-ci.yml@main
    with:
      branch: "develop"

  ci-feature:
    if: contains(github.ref, 'refs/heads/feature/')
    uses: org/reusable-workflows/.github/workflows/reusable-ci.yml@main
    with:
      branch: ${{ github.ref }}