# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/*"

jobs:
  call-reusable-workflow:
    uses: org/rfi-workflows/.github/workflows/CI.yml@master
    with:
      branch: ${{ github.ref }}
